Update next js libraries, add new libraries
Mateusz966/agsl pull request #2
Opened 2023-02-08 18:06 UTC by victsob98

2023-02-09 18:53 UTC, Mateusz966 commented on admin/package.json
> +    "react-query": "^3.39.3"
To może wylecieć wersja jest to poprzednia wersja "@tanstack/react-query"

2023-02-09 18:54 UTC, Mateusz966 commented on admin/package.json
> +    "@emotion/styled": "^11.10.5",
Wywaliłbym te paczki, one były przy okazji chakry (ale możesz sprawdzić jeszcze)

2023-02-09 18:55 UTC, Mateusz966 commented on admin/package.json
> +    "@mantine/hooks": "^5.10.3",
Na pewnoe nie chcemy wrzucić sobie więcej paczek? Spokojnie możemy dodac modale, daty oraz notyfikacje
![image](https://user-images.githubusercontent.com/37120337/217910103-de8bc153-f611-4765-b93c-0f8cf8bffed6.png)

2023-02-09 18:56 UTC, Mateusz966 commented on admin/package.json
> +    "framer-motion": "^9.0.2",
Czy tą paczke też potrzebujemy? ;D

2023-02-09 19:01 UTC, Mateusz966 commented on mobile/package.json
> +    "@react-navigation/native": "^6.1.3",
Chyba brakuje tego z docsów jak patrzę ;)
![image](https://user-images.githubusercontent.com/37120337/217912004-59493ead-c0dd-4169-92a1-365ce42d4531.png)

2023-02-09 19:03 UTC, Mateusz966 requested changes
Kilka rzeczy w komentarzach pozdrawiam :). XD

2023-02-10 17:46 UTC, victsob98 commented on admin/package.json
> +    "@mantine/hooks": "^5.10.3",
właśnie nie byłam pewna jakie chcemy dodawać, także czekałam na response

2023-02-10 17:53 UTC, victsob98 commented on admin/package.json
> +    "@emotion/styled": "^11.10.5",
sprawdzone - do wywalenia

2023-02-11 12:38 UTC, Mateusz966 approved these changes
very good job

2023-02-11 12:42 UTC, merged