Serverless framework
Mateusz966/agsl pull request #49
Opened 2024-10-30 07:37 UTC by Mateusz966

2024-11-04 08:00 UTC, victsob98 requested changes

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/functions/auth/event.schema.ts
> +export const registerSchema = z.object({
shouldn't we add nick to the register schema?

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/functions/auth/login/handler.ts
> +  .use(zodValidator(registerSchema))
so login schema will be the same as register schema?

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/functions/auth/login/handler.ts
> +    region: "eu-central-1",
maybe it will be better to store this in a const? same as AuthFlow below

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/functions/auth/register/handler.ts
> +    UserAttributes: [{ Name: "email", Value: email }],
what about password?

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/functions/dish/get-dishes/handler.ts
> +export const dishHandler = async () => {
dishes or dishlist

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/functions/migrations/handler.ts
> +  await connectToDb;
why you're not calling the function?

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/migrations/1730148420238-migration.ts
> +import { MigrationInterface, QueryRunner } from "typeorm";
why are there two the same migrations?

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/shared/errors/http.error.ts
> +import { StatusCodes, getReasonPhrase } from "http-status-codes";
nice one

2024-11-04 08:00 UTC, victsob98 commented on server-v2/app/shared/middleware/zod-validator.ts
> +    if (!parserResult.success) {
are there any other properties like failed? could be used insted of negation - or reverse the condition

2024-11-04 21:09 UTC, Mateusz966 commented on server-v2/app/functions/auth/login/handler.ts
> +  .use(zodValidator(registerSchema))
my mistake, i changed to loginSchema :D

2024-11-04 21:35 UTC, Mateusz966 commented on server-v2/app/functions/auth/register/handler.ts
> +    UserAttributes: [{ Name: "email", Value: email }],
We don't need password as attribute, we are looking for user and return token if we found in cognito. We connect user from cognito with our user by externalId (cognito id in our app)

2024-11-05 20:42 UTC, victsob98 commented on server-v2/app/functions/auth/register/handler.ts
> +    region: "eu-central-1",
It could also be derived from config, same as in login file

2024-11-07 08:40 UTC, Mateusz966 commented on server-v2/app/functions/auth/login/handler.ts
> +    region: "eu-central-1",
Good idea, i will add region to the env file

2024-11-07 12:00 UTC, Mateusz966 commented on server-v2/app/shared/middleware/zod-validator.ts
> +    if (!parserResult.success) {
Zod returns `success: true or false` here, and in my opinion, this line is readable as is, so no changes are needed :D

2024-11-13 18:45 UTC, Mateusz966 commented on server-v2/app/functions/migrations/handler.ts
> +  await connectToDb;
connectToDb is promise we just waiting for our connection to establish

2024-11-13 18:50 UTC, Mateusz966 commented on server-v2/app/migrations/1730148420238-migration.ts
> +import { MigrationInterface, QueryRunner } from "typeorm";
I don't know, those files are generated by typeorm when compare class

2024-11-13 18:51 UTC, victsob98 approved these changes

2024-11-13 19:06 UTC, merged